from .sensor import router as sensor_router
from .datastream import router as datastream_router
from .measurement import router as measurement_router
from .authentication import router as authentication_router
from .user import router as user_router
from .event import router as event_router
from .health import router as health_router
from .trafficlanes import router as trafficlanes_router
from .walkability import router as walkability_router
from .bikeability import router as bikeability_router
from .event_datastreams import router as event_datastream_router
from .event_measurements import router as event_measurement_router
